server:
  port: 9091

eureka:
    client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: RESTAURANT-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurantdb?createDatabaseIfNotExist=true&useSSL=false
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    livereload:
      enabled: true
      port: 35729