server:
  port: 9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: FOOD-CATALOGUE-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/fooddb?createDatabaseIfNotExist=true&useSSL=false
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    livereload:
     enabled: false
     port: 35729
